### ISSUE TITLE
Need some documentation on how to interface with Live Score App

### ISSUE THREAD

**Issue by JoshuaCarroll** [JoshuaCarroll/Fairplay-to-LiveScoreApp-Bridge#1]
@boxblinkracer,

I was trying to emulate the JSON data stream that ScoreboardOCR sends.  I have the payload formatted the same, and I tried to create a TCP connection to port 8080 and write the payload.  Live Score App acknowledged the connection, but never acted like it received the data.  Do I have to disconnect after sending data each time or send an ETX signal or... ??

**Comment by boxblinkracer** [comment]
hey
wow, nice work
mhm....lets connect with email, can you send me the file there?
